In [ ]:
# view lastfm_tags.db    
# view track_metadata.db   


#!/usr/bin/env python
# -*- encoding: utf-8 -*-

# USAGE:
#   python Lab1.py Sample_Song_Dataset.db

import sys
import sqlite3
import time


# The database file should be given as the first argument on the command line
# Please do not hard code the database file!
db_file = sys.argv[1]


# We connect to the database using 
with sqlite3.connect(db_file) as conn:
    # We use a "cursor" to mark our place in the database.
    # We could use multiple cursors to keep track of multiple
    # queries simultaneously.
    cursor = conn.cursor()
    cursor.execute('show tables')
    
    print(cursor.fetchall())

In [ ]:
#!/usr/bin/env python
# -*- encoding: utf-8 -*-

# USAGE:
#   python Lab1.py Sample_Song_Dataset.db

import sys
import sqlite3
import time


# The database file should be given as the first argument on the command line
# Please do not hard code the database file!
db_file = sys.argv[1]


# We connect to the database using 
with sqlite3.connect(db_file) as conn:
    # We use a "cursor" to mark our place in the database.
    # We could use multiple cursors to keep track of multiple
    # queries simultaneously.
    cursor = conn.cursor()

    # This query counts the number of tracks from the year 1998
    year = ('1998',)
    cursor.execute('SELECT count(*) FROM tracks WHERE year=?', year)

    # Since there is no grouping here, the aggregation is over all rows
    # and there will only be one output row from the query, which we can
    # print as follows:
    print('Tracks from {}: {}'.format(year[0], cursor.fetchone()[0]))
    # The [0] bits here tell us to pull the first column out of the 'year' tuple
    # and query results, respectively.

    # ADD YOUR CODE STARTING HERE
    d_1 = 'DROP INDEX IF EXISTS ind_tracks'
    cursor.execute(d_1)
    d_2 = 'DROP INDEX IF EXISTS ind_artists'
    cursor.execute(d_2)
    d_3 = 'DROP INDEX IF EXISTS ind_term'
    cursor.execute(d_3)
    
    
    # QUESTION 1
    q_1_title = ('Silent Night (Album)',)
    q_1 = '''
        SELECT a.artist_id, a.artist_name, t.term
        FROM artists as a
        INNER JOIN artist_term as t
        ON a.artist_id = t.artist_id
        INNER JOIN tracks as tk
        ON a.artist_id = tk.artist_id
        WHERE tk.title = ?
        '''
    cursor.execute(q_1,q_1_title)
    print('(Q1) Silent Night (Album) Table: {}'.format(cursor.fetchall()))
    print('----------------')

    
    # QUESTION 2
    q_2 = '''SELECT DISTINCT title
        FROM tracks 
        WHERE duration < 3
        '''
    cursor.execute(q_2)
    print('(Q2) Unique Track Titles Less Than 3 Seconds Table: {}'.format(cursor.fetchall()))
    print('----------------')
    
          
    # QUESTION 3
    q_3 = '''SELECT track_id
        FROM tracks
        WHERE year > 2008 and year < 2012
        ORDER BY duration DESC
        LIMIT 10'''
    cursor.execute(q_3)
    print('(Q3) 10 Longest Tracks between 2008 and 2012: {}'.format(cursor.fetchall()))
    print('----------------')
    
    
    # QUESTION 4
    q_4 = '''SELECT term, count(term) as 'Term_Count'
        FROM artist_term
        GROUP BY term
        ORDER BY Term_Count, term ASC
        LIMIT 15'''
    cursor.execute(q_4)
    print('(Q4) 15 Least Used Terms: {}'.format(cursor.fetchall()))
    print('----------------')
    

    # QUESTION 5
    q_5 = '''SELECT a.artist_name
        FROM artists as a
        LEFT JOIN tracks as tk
        ON a.artist_id = tk.artist_id
        ORDER BY tk.duration ASC
        LIMIT 1'''
    cursor.execute(q_5)
    print('(Q5) Artist with Shortest Track: {}'.format(cursor.fetchall()))
    print('----------------')
    
    
    # QUESTION 6
    q_6 = '''SELECT avg(duration) FROM tracks'''
    cursor.execute(q_6)
    print('(Q6) Mean Duration of Tracks: {}'.format(cursor.fetchall()))
    print('----------------')
    
    
    # QUESTION 7
    q_7 = '''SELECT tk.track_id
        FROM tracks as tk
        INNER JOIN artist_term as t
        ON tk.artist_id = t.artist_id
        GROUP BY t.artist_id, tk.track_id
        HAVING count(t.term) > 8
        ORDER BY tk.track_id
        LIMIT 10'''
    cursor.execute(q_7)
    print('(Q7) Tracks from Artists with More Than 8 Terms: {}'.format(cursor.fetchall()))
    print('----------------')
    
    
    # QUESTION 8
    t = []
    for i in range(100):
        start = time.time()
        cursor.execute(q_1, q_1_title)
        end = time.time()
        tot_t = end-start
        t.append(tot_t)
        
    print(f'(Q8) Min Pre-Indexing: {min(t)}')
    
    ind_1 = 'CREATE INDEX ind_tracks ON tracks(artist_id)'
    cursor.execute(ind_1)
    ind_2 = 'CREATE INDEX ind_artists ON artists(artist_id)'
    cursor.execute(ind_2)
    ind_3 = 'CREATE INDEX ind_term ON artist_term(artist_id)'
    cursor.execute(ind_3)
    
    t = []
    for i in range(10):
        start = time.time()
        cursor.execute(q_1, q_1_title)
        end = time.time()
        tot_t = end-start
        t.append(tot_t)
        
    print(f'(Q8) Min Post-Indexing: {min(t)}')
    print('----------------')
    
    
    # QUESTION 9
    cursor.execute('BEGIN TRANSACTION')
    del_trans = '''
        DELETE  FROM tracks
        WHERE track_id IN (select tks.track_id AS 'track_id'
        from tracks as tks
        join artist_term as t
        on tks.artist_id = t.artist_id
        where t.term = 'europop')
        '''
    cursor.execute(del_trans)
    print(f'(Q9) Rows effected pre-rollback: {cursor.rowcount}')
    cursor.execute('ROLLBACK')